import AppKit
import UniformTypeIdentifiers

/// Reads the current pasteboard into a `CaptureCandidate`, in priority order,
/// while skipping content that should never be captured (passwords/transient).
enum PasteboardReader {

    private static let concealedMarkers: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    private static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")

    static func read(_ pasteboard: NSPasteboard) -> CaptureCandidate? {
        guard let types = pasteboard.types else { return nil }

        // Respect password managers and transient content.
        if !concealedMarkers.isDisjoint(with: Set(types)) { return nil }

        let sourceURL = pasteboard.string(forType: sourceType)
        let sourceApp = NSWorkspace.shared.frontmostApplication?.localizedName

        // Priority: image data > file URL > web URL > plain string.
        if let data = pasteboard.data(forType: .png) {
            return CaptureCandidate(payload: .image(data), sourceApp: sourceApp, sourceURL: sourceURL)
        }
        // Carry raw TIFF bytes as-is — do NOT re-encode to PNG here. The old
        // `NSBitmapImageRep` decode+encode ran on the main-thread clipboard poll
        // and could stall the UI for large screenshots. CGImageSource reads TIFF
        // natively, so the thumbnail (save path) and the nudge preview both
        // downsample it off the main thread.
        if let tiff = pasteboard.data(forType: .tiff) {
            return CaptureCandidate(payload: .image(tiff), sourceApp: sourceApp, sourceURL: sourceURL)
        }

        if let urls = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL], let url = urls.first {
            if url.isFileURL {
                return CaptureCandidate(payload: .file(url), sourceApp: sourceApp, sourceURL: sourceURL)
            } else if let scheme = url.scheme?.lowercased(), scheme == "http" || scheme == "https" {
                return CaptureCandidate(payload: .url(url), sourceApp: sourceApp, sourceURL: sourceURL)
            }
        }

        if let string = pasteboard.string(forType: .string), !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return CaptureCandidate.fromString(string, sourceApp: sourceApp, sourceURL: sourceURL)
        }

        return nil
    }
}
